### ISSUE TITLE
Two licenses?

### ISSUE THREAD

**Issue by FlashDaggerX** [CCSU-DesignPatterns/DesignPatternsCourseMaterial#2]
Just curious as to why there's two different licenses for this repo (I'm assuming the intended license is `LICENSE.txt` which contains the OER license).

Or does the OER license not apply to the code used in this repo (in which case, I can see why the MIT license might be present)?

**Comment by caw13** [comment]
@FlashDaggerX I have been told by those in the OER community that both should be used for a project such as this.  The MIT license is the one most appropriate for the code demos, whereas the Creative Commons Attribution-ShareAlike license is more appropriate for the lecture/content slides.
